### ISSUE TITLE
Refactor AdaptiveColumnBuilder to support further column types

### ISSUE THREAD

**Issue by monsterkrampe** [knowsys/nemo#10]
The `AdaptiveColumnBuilder` is currently implemented to decide the use of a `RleColumn` vs a `VectorColumn` based on the data that the `AdaptiveColumnBuilder` receives.
The current solution may not be suitable when further column types shall be supported.

This issue provides a place for discussion on refactoring possibilities. Some discussion also already happened in #8.
Once a decision is made, the implementation can happen in the scope of this issue.
Maybe, it is worthwhile to postpone the discussion until another column type is actually to be supported by the `AdaptiveColumnBuilder`. In this sense the issues acts as a mere reminder.

**Comment by mmarx** [comment]
In light of #166 and #167, is this still open?

**Comment by monsterkrampe** [comment]
I think this issue may only become relevant when we add another column type besides `Rle` and `Vec`.
I'd say, we can close this one. If there will be another column type, we will have an issue for that one anyway where we can also handle this problem.
