### ISSUE TITLE
Single quotes vs. double quotes in CSV

### ISSUE THREAD

**Issue by larry-gonzalez** [knowsys/nemo#105]
On commit 846a72c

How does stage2 interprets the single quote and quote characters in datasets?

Look the results that I get:

### Example 1

Consider the program:
```
@source p[2]: load-csv(".../data/p.csv") .

p(?Y,?X) :- p(?X,?Y) .
p(?X,?Z) :- p(?X,?Y),p(?Y,?Z) .
```
And the data in file `p.csv`:
```
a,b
"b","c"
'c','d'
```
The following are the results that I get after executing `stage2`:
```
a,a
a,b
a,c
b,a
b,b
b,c
c,a
c,b
c,c
'c','c'
'c','d'
'd','c'
'd','d'
```

There you can see that the characters `'c'` and `c` are interpreted differently

### Example 2:
Consider the program (same program but for predicate q):
```
@source q[2]: load-csv(".../data/q.csv") .

q(?Y,?X) :- q(?X,?Y) .
q(?X,?Z) :- q(?X,?Y),q(?Y,?Z) .
```

And the data
```
e,\"
"\"",f
```

The following are the results that I get after executing `stage2`:
```
e,e
e,\"
\",e
\",\"
```

Which (a) does not materialize everything, and (b) deletes one of the original rows in the dataset

-----

Hence I ask, are single quotes and quotes supported by stage2?

**Comment by mmarx** [comment]
Closing in favour of #109.
