### ISSUE TITLE
Handle single and double quote in csv files identically

### ISSUE THREAD

**Issue by ellmau** [knowsys/nemo#109]
As discussed in #105 the serde library does not support multiple signs for escaped sequences.

To be uniform with RDF string handling, single quotes and quotes should both be handled as valid escape sequences. 

### Example 
```
a, "b,c", 'd,e'
```
is currently parsed into 4 fields: `[ "a", "b,c", "'d", "e'" ]`, while it should be 3 fields: `[ "a", "b,c", "d,e"]`

One possible solution is to inject another reader to sanitize the csv input line by line before letting serde csv parse the csv content.

**Comment by monsterkrampe** [comment]
We do not plan to support both `"` and `'` at the same time.
