### ISSUE TITLE
Change command-line parameter name for output directory

### ISSUE THREAD

**Issue by mkroetzsch** [knowsys/nemo#175]
Instead of the current -o/--output parameters, we should use the following:
```
-D, --output-dir=<DIR>   Specify directory for output files.
```
This should default to "." This will align that option with Souffle and Formulog. As part of the change to use . as default directory, the behavior of ```--overwrite-results``` should change to overwrite only the files that are newly generated, and to leave all other files in the directory unchanged. In general, the behaviour of deleting everything in a directory with this option seems quite dangerous and easy to overlook.

Later, there should also be a revision of the current ```-s``` option, but this depends on the availability of output directives as per #174.

**Comment by monsterkrampe** [comment]
I'm a little worried about having `.` as the default. If the `.csv` files are in the same directory as the `.rls` file and if one executes `nmo` in this directory, then the input `.csv` files might be overwritten if there are new facts derived for them. Having a subdirectory, e.g. `./results/` as a default makes this less likely.

**Comment by monsterkrampe** [comment]
Note on `--overwrite-results`: As of now (opposed to what is claimed in the description of the flag), the output directory is not emptied but existing files are only overwritten if there is a new output file with the same name. So this option does not need to change (only its description needs adjustment).

**Comment by ellmau** [comment]
> Note on `--overwrite-results`: As of now (opposed to what is claimed in the description of the flag), the output directory is not emptied but existing files are only overwritten if there is a new output file with the same name. So this option does not need to change (only its description needs adjustment).

Yes I did change the behaviour with one of the io updates after I got first feedback on this.  Somehow this description has survived the changes.
