### ISSUE TITLE
Delegation of Trait Implementations

### ISSUE THREAD

**Issue by monsterkrampe** [knowsys/nemo#19]
For our custom types `Float` and `Double`, we have to delegate quite a lot of trait implementations to the underlying `f32` and `f64` types, respectively. I played around with [delegate](https://crates.io/crates/delegate) and [ambassador](https://crates.io/crates/ambassador) a bit but I did not achieve satisfying results here.

This is not a pressing issue at all but it would be nice to have if we can find a nice way to shorten those delegations.
Feel free to experiment here :)

**Comment by mmarx** [comment]
Is this still something that needs solving?

**Comment by monsterkrampe** [comment]
If there should be a new language feature in the future that makes delegations easier, we might reconsider this but before that there is not much that can be done :)
