### ISSUE TITLE
Support overloading of predicates with different arities or different types

### ISSUE THREAD

**Issue by mmarx** [knowsys/nemo#194]
When trying to reason over a rule set that uses the same predicate name with different arities (such as the one below), a panic occurs in src/logical/execution/planning/plan_util.rs:184 (index out of bounds: the len is 1 but the index is 1).

```prolog
p(?X) :- fact(?X) .
p(?X, ?X) :- fact(?X) .
fact(X) .
```

**Comment by monsterkrampe** [comment]
We currently do not plan to have this feature.
