### ISSUE TITLE
Unify handling of angled brackets in CSV and rules files

### ISSUE THREAD

**Issue by aannleax** [knowsys/nemo#199]
Currently, the parser interprets the expression `constant` in a rule or fact as an IRI and normalizes it to `<constant>`. However, the same does not happen when parsing CSV files. This has the annoying effect that constants used in input files cannot be referenced by rules unless they are enclosed by angled brackets.

**Comment by monsterkrampe** [comment]
After some offline discussion, we want to change the internal normalization to omit the angle brackets `<...>` for (relative) iris as often as possible. For (relative) iris starting with a number, we would still keep them to not interfere with the string representation of actual numbers that should just be represented as their stringified version.
Actual string literals that are not (relative) iris should be wrappen in quotes, potentially even with `"..."^^xsd:string`.
