### ISSUE TITLE
Crash on empty values in CSV

### ISSUE THREAD

**Issue by mkroetzsch** [knowsys/nemo#213]
Nemo crashes when loading data from a CSV file that contains empty cells (two commas with nothing in between). Such cases should be interpreted as empty strings in RdfResource, and indexed accordingly (probably as ```""```).

It would be ok for the dictionary to reject empty strings (i.e., really empty strings, rather than the above encoding of the empty string literal), but it should do so more gracefully and without crashing the application.

**Comment by monsterkrampe** [comment]
Potentially solved by #211 (I'll add another test).
