### ISSUE TITLE
Redesign error messages

### ISSUE THREAD

**Issue by mmarx** [knowsys/nemo#219]
Rework the way error messages are displayed to the user. Errors should ideally be easy to identify, be concise, yet still understandable. In particular, we might want to simplify the formatting of parse errors to
* more clearly show the exact portion of the input that caused the error, and
* likely only show the top-level error, unless verbosity is increased.

**Comment by mmarx** [comment]
Instead of the top-level parse error, we might also want to have the most-specific (i.e., bottom-most) non-`SyntaxError` parse error, which should be closer to the actual problem. More generally, consider reversing the order we show the errors in.

**Comment by monsterkrampe** [comment]
Should be addressed by #455
