### ISSUE TITLE
Rust API for reasoning tasks

### ISSUE THREAD

**Issue by ellmau** [knowsys/nemo#228]
To use the nemo library for reasoning tasks, a rudimentary API would be needed.

# API
A MVP for this includes the following functionality. Note that this is the absolute minimum and more features can (and should be) added later.

## load rule file (parts)
This shall take a given string and parse it like any given input-program.
In contrast to the current model, where the whole program is loaded in one step,
incremental calls with different rules shall be possible.
A parse-error should be reported back and only this call of the load-directive shall be rolled back.
## reasoning
Calling the actual reasoning process, which includes reading of external resources and creating the full reasoning closure of the given program.
## query
Query some results from the reasoning process and provide ways to view the results.
This can be an object model representation of the result, as well as direct access to the efficient writing methods, already available (i.e. csv output writer)
## reset
Reset the state of the reasoning engine, where no rules have been loaded and no conclusions have been drawn.

# Architecture
It will be necessary to track the state of the input and the parsed rule model. A way to roll back/commit changes to the already parsed rules need to be introduced as well.

**Comment by mmarx** [comment]
Landed as part of #236.
