### ISSUE TITLE
Implement Mapping from Physical Representation of Any to RDF Terms

### ISSUE THREAD

**Issue by monsterkrampe** [knowsys/nemo#245]
The RDF terms in the logical `Any` columns are stored in a string representation in the physical layer. Currently, our output just writes this representation to CSV since it happens to be exactly what we want to have in the CSV.
In general, we want the possibility to get the original RDF term back from the physical string representation.
To be more precise, we want something like the inverse of `LogicalTypeEnum::ground_term_to_data_value_t`.
To be super clean, we would want to use this method also when writing CSV files but we have to be careful to not create wrapper objects for every value since CSV writing is very much performance critical. Maybe an idea similar to the `BuilderProxy` solution could be helpful.

**Comment by mkroetzsch** [comment]
Not sure how the architecture with a proxy object might work. To avoid the need to make value objects, it would have to work with the physical level types as inputs. So you would maybe need methods like ```writeString()``` and ```writeAny``` that get the internal physical value and turn this into correct CSV output. But this logic would belong to the CSV output writer and not really be a proxy object ... In a way, we are making the inverse of the reading method "create a physical data value based on a CSV string value given a logical datatype", namely: "create a CSV string value based on a physical data value given a logical datatype". And this functionality is not in the proxy object in the reading direction either.

Also note that, as in reading, it could happen in theory that the conversion fails (some physical values may be impossible to write in the format, even if they have the correct physical datatype).

**Comment by matzemathics** [comment]
Another idea that might help is to make the dictionary smarter, for example allow storing tags, which type was inferred upon saving.

**Comment by mmarx** [comment]
This should probably be solved before starting #275.
