### ISSUE TITLE
Missing inferences with stratified negation

### ISSUE THREAD

**Issue by mkroetzsch** [knowsys/nemo#265]
Nemo misses some inferences in certain programs with stratified negation. Here is a minimal example:
```
p1(a).
p1(b).
p2(a).

q1(?X) :- p1(?X).
q2(?X) :- p2(?X).

q(?X) :- q1(?X), ~q2(?X).

r(?X) :- q(?X).
```

The result correctly has ```q1(a)```, ```q1(b)```, ```q2(a)```, and ```q(b)```. However, ```r(b)``` is missing.

**Comment by matzemathics** [comment]
Interesting, the resulting stratification of this program is `[[0, 1, 3], [2]]`, so the dependency between rule 2 and 3 is ignored for some reason.
