### ISSUE TITLE
Use Logical Types and Source Types to decide which Builder Proxy to use for CSV and other Readers

### ISSUE THREAD

**Issue by monsterkrampe** [knowsys/nemo#280]
As of now, the CSV reader only accepts a list of logical types and decides which builder proxies to use only based on that.
Additionally there is some hack write know that still uses the `String` Builder Proxy if the logical type is `Any` and the corresponding source type is `String`.
To make this more flexible, one could maybe pass Proxy Builders to the reader directly instead of only the logical types.

**Comment by mmarx** [comment]
> To make this more flexible, one could maybe pass Proxy Builders to the reader directly instead of only the logical types.

But doesn't the input format also have an influence on what builder proxy is the correct one?

**Comment by monsterkrampe** [comment]
True, is is another factor. I'm not sure what will be the best solution here. The main point of this issue is to take the source types into account properly and clean up the hack which I currently implemented.
