### ISSUE TITLE
Implement logical type casting for primitive types in reasoning process (Any, String, Integer, Float64)

### ISSUE THREAD

**Issue by monsterkrampe** [knowsys/nemo#282]
At the moment, only `Any` and `String` are compatible because they happen to have the same physical representation.
We also want that at least `Integer` and `Float64` are also compatible with `Any`. For this, it is crucial to be able to cast e.g. physical `Integer` presentations into physical `Any` presentations.

Consider two unary predicates `A,B` of type `Any` and `Integer`. There are two different cases where typecasting is needed:
1. `A(x) :- B(x).` - The values that are put in `A` need to be casted to `Any`.
2. `... :- A(x), B(x)` - There needs to be a way to compare values of type `Any` with values of type `Int`.

**Comment by aannleax** [comment]
Arbitrary data types in each column is now supported. Special functions for casting between different (logical) datatypes have been added.
