### ISSUE TITLE
Implement full type hierarchy of primitive types (Any, String, Integer, Float64)

### ISSUE THREAD

**Issue by monsterkrampe** [knowsys/nemo#283]
Currently only `Any` and `String` are compatible. `Integer` and `Float64` are only compatible with themselves but should actually also be compatible with `Any`. The type inference shall take this into account by probably defining an appropriate partial order on those types.

**Comment by monsterkrampe** [comment]
This is currently blocked by #280.

**Comment by aannleax** [comment]
The new `AnyDataValue` takes care of this
