### ISSUE TITLE
Relax ordering requirements for declarations and statements in rule files; improve error messages

### ISSUE THREAD

**Issue by matzemathics** [knowsys/nemo#284]
Example:
```
@source a[3]: load-csv("something.csv").
@declare a(integer, string, any).
```
gives error
```
Parse error on line 2, column 1: Syntax error: End of file
```

Expected behaviour:
Either accept the above, or something like
```
Parse error on line 2, column 1: Syntax error: @declare used after @source
```

**Comment by matzemathics** [comment]
Ok, I just noticed the "problem" is more general than this, because the program is expected to be structured into parts that have a fixed order which is

1. base prefix
2. prefix declarations
3. datatype declarations
4. data source declarations
5. the actual program

I don't know if we want to stick with this strict requirement. In any case the error messages should be more helpful here.

**Comment by mmarx** [comment]
No, we should relax the restrictions somewhat (we already concluded that we want to allow `@output` at places other than the exact end of the program), and have better error messages for the cases where, e.g., a base declaration is found after a relative IRI appeared in some fact or rule.
