### ISSUE TITLE
Public API for adding sources to an `ExecutionEngine`

### ISSUE THREAD

**Issue by matzemathics** [knowsys/nemo#318]
Currently the only sources available during program execution are the ones specified by the program. It should be possible to dynamically add sources after loading the program (before the execution starts).

**Comment by matzemathics** [comment]
Related to #316

**Comment by mmarx** [comment]
> It should be possible to dynamically add sources after loading the program (before the execution starts).

Maybe I'm missing something obvious, but how could those ever be relevant to program execution, since they are … not mentioned by the program?

**Comment by matzemathics** [comment]
> Maybe I'm missing something obvious, but how could those ever be relevant to program execution, since they are … not mentioned by the program?

I think for features like #316 it would be nice to have the option to just add sources to a predicate dynamically (whether that is via cli or language bindings).

That does however affect program analysis, so we might need to introduce some syntax for this (maybe 'input'?).

**Comment by mmarx** [comment]
I see. So this could also be useful to test a module (once we actually have those) in isolation. There, it would obviously be `@input`, but for regular programs, I'm not sure we need additional syntax – we have type inference and `@declare`, is that not enough?

**Comment by mmarx** [comment]
Shouldn't we rather do the analysis after we know what the sources will be?

**Comment by mmarx** [comment]
We think that most of this would be covered by adding methods to `Program` that allow modification (`add_rule`, `add_source`, `sources_mut`, e.g.). Analyses would then be performed when converting to a `ChaseProgram` (effectively treating the whole rule model as a somewhat complex builder).

**Comment by matzemathics** [comment]
Superseded by #346
