### ISSUE TITLE
Duplication of Intermediate Table Structures During Loading

### ISSUE THREAD

**Issue by aannleax** [knowsys/nemo#322]
Currently, during loading we store the intermediate structure as a `Vec<VecT>` which is later converted into a `Trie`. During this translation we need to sort the data. Both versions of this intermediate structure, the sorted and the unsorted ones, are being held in memory at the same time. This presents a problem when dealing with large input files.

Maybe one could do some in-place sorting to avoid this memory spike.

**Comment by larry-gonzalez** [comment]
Just as a patch solution:

a call to `drop(cols)` right after [trie.rs#L369](https://github.com/knowsys/nemo/blob/main/nemo-physical/src/tabular/table_types/trie.rs#L369) will free the original data

There would be still a time frame in which Nemo would keep in memory both: the sorted columns, and the trie structure

**Comment by mmarx** [comment]
For what it's worth, neither #323 nor the in-place sorting in 320f09d5bd2ac67da42bf63616e43796e2e796c4 seem to have any effect on total memory consumption (as shown by `massif` on the 10 Million Wikidata triples). On smaller tables (e.g., `galen`), in-place sorting is also noticeably slower.

**Comment by larry-gonzalez** [comment]
Interestingly, I can report less memory consumption when calling `drop(cols)`

I am building Nemo in release mode, and measuring available memory in different points inside the function `Trie::from_cols` using `sysinfo` crate

When loading a csv file (300M lines, 5.9G uncompressed) containing only numeric ids, Nemo uses overall ~6GB less memory when the `drop(cols)` is executed

**Comment by matzemathics** [comment]
I think this should now be resolved by #344 , which streams the sorted values into the builders, instead of collecting them before.
