### ISSUE TITLE
Support equality of two integer variables

### ISSUE THREAD

**Issue by Laschoking** [knowsys/nemo#355]
For me this snipped does not work.
```
@declare foo1(integer).
@declare foo2(integer).
@declare intInBody(integer,integer).
foo1(1). foo2(2).
intInBody(?a,?b):-
    foo1(?a),
    foo2(?b),
    ?a = ?b.
```
Throwing the following error message:
```rust
thread 'main' panicked at nemo/src/execution/planning/plan_util.rs:35:39:
called `Option::unwrap()` on a `None` value
``` 
The other cases are working:
- inequality of two integer variables
- equality & inequality of one integer literals with one integer variables

**Comment by matzemathics** [comment]
That is a bug in the normalization code: the head of the rule is not updated after normalization of the body.
