### ISSUE TITLE
Refactor `Term` model

### ISSUE THREAD

**Issue by matzemathics** [knowsys/nemo#360]
currently the `Term` type contains a lot of different things, which do not necessarily play nicely together:
- it is used as the type of values, that are returned from the logical layer when iterating through a table
- yet it also contains variables and even aggregates, which do not make sense in the above context
- however it does _not_ contain arithmetic operations, which are encoded using the separate `TermTree` type (even though they too could reosonably referred to as "terms")

I propose the following model:

```rust
enum Term {
  /// An arithmetic operation, aggregation or function call
  Operation {
    /// The operation to be performed
    operation: TermOperation,
    /// The arguments to the operation
    subterms: Vec<Term>
  },
  /// A (universal or existential) variable
  Variable(Variable),
  /// A constant of type primitive
  Constant(PrimitveValue),
}

enum PrimitiveValue {
  /// An (abstract) constant.
  Constant(Identifier),
  /// A numeric literal.
  NumericLiteral(NumericLiteral),
  /// A string literal.
  StringLiteral(String),
  /// An RDF literal.
  RdfLiteral(RdfLiteral),
}
```

Notably, I would propose to make aggregations a special case of `TermOperation` instead of a seperate thing. @rlwww do you see any problems with this?
Another thing to keep in mind is that while we only support primitive constants right now, the API that returns values from tables will need something to represent the `Any` type, so something like this might be added:

```rust
enum AnyValue {
  /// A value of type primitive
  Primitive(PrimitiveConstant),
  // other complex values...
}
```

That way there is a clean seperation between a `Term`, which is a parsed representation of user input, and a computed `AnyValue`, which is what comes out at the end of reasoning and can be serialized into various formats.

**Comment by matzemathics** [comment]
I have looked at the definition of aggregate again, since it currently only supports variables as subterms, it might make sense to have a special case for that.

**Comment by aannleax** [comment]
I like the overall idea, but I don't get the point behind the additional `AnyValue` structure to separate "user input" from "computed values". Why shouldn't "`// other complex values...`" be written by the user? Is "Any" the only exception (although, if we allow implicit type declarations via constants (like writing `A(1, 2.0)` to imply `@declare A(integer, float64)`), it's not unreasonable to allow something like `B(Any::Integer(1))` and have it imply `@declare B(any)`., so I'm not even sure if it should be an exception)?

**Comment by mkroetzsch** [comment]
This is a good point. I think we should keep a very syntactic enum (or a set of such enums) that is suitable for representing what was written in code, which can be a function, an aggregate, or a more direct syntactic representation of some "value".

What we miss besides this is a semantic representation of logical level values. A value is an element of our semantic domain, which also can contain structured objects, such as function terms. But it still is different in that there is no ambiguity ever (e.g., the syntax "42.3" might ambiguously represent a decimal or a float or a double etc. -- this is just an example and may not correspond to current/planned design). So each "semantic" value is just that: a piece of structure that we use "as given".

Another way to see the difference is that syntactic terms are things we might find in input rule files, whereas logical values are the things that might be returned when querying the database.

There is a lot of overlap between the two worlds, but it would help a lot to keep them strictly apart in the API, using different rust types. Then the syntactic processing and the logical query answering are not tied to agree on a single API or internal representation.

I am not sure if `PrimitiveValue` above is roughly the "logical value" whereas `Term` is the syntactic term. I like "term" and "value" as keywords for distinguishing syntax and semantics, but "primitive" seem to be a special case.

**Comment by matzemathics** [comment]
> There is a lot of overlap between the two worlds, but it would help a lot to keep them strictly apart in the API, using different rust types. Then the syntactic processing and the logical query answering are not tied to agree on a single API or internal representation.

Agreed, in particular I believe that the public part of our API probably won't be concerned with `Term` at all, because that is just an internal syntax representation.
