### ISSUE TITLE
Add more tests for arithmetic operations

### ISSUE THREAD

**Issue by matzemathics** [knowsys/nemo#381]
Currently body expressions have no end-to-end tests (as far as I am aware) and the test coverage of head and constraint expressions is very minimal.

**Comment by aannleax** [comment]
The file https://github.com/knowsys/nemo/blob/main/resources/testcases/arithmetic/builtins.rls now contains a test for all supported builtin functions. Also there are unit tests for each of them in https://github.com/knowsys/nemo/blob/main/nemo-physical/src/function/evaluation.rs.
