### ISSUE TITLE
Attempt to upgrade values to `any` leads to unreachable code being executed.

### ISSUE THREAD

**Issue by matzemathics** [knowsys/nemo#394]
Example:
```prolog
values(42).

@declare result(any).
result(?v) :- values(?v).
```
The type inference (correctly) infers the type of `values` should be `integer`. However it does not complain, that there is currently no support for casting integers into `any`, eventually reaching unreachable code.
```
thread '<unnamed>' panicked at nemo/src/model/types/primitive_logical_value.rs:407:18:
internal error: entered unreachable code: If the database representation of the logical types is correct, we never reach this branch.
```

**Comment by monsterkrampe** [comment]
Nice find!
Seems like `replace_with_max_type_if_compatible` is currently allowing to many "compatibilities".
I will look into it :)
