### ISSUE TITLE
Machine-readable traces

### ISSUE THREAD

**Issue by stefborg** [knowsys/nemo#403]
We would like to get traces in a machine-readable format, e.g. JSON, to process them further outside of Nemo. As a suggestion, the following is adapted from the hypergraph-based format we are currently using for description logic proofs in evee:
```
{
  "finalConclusion" : "A(a)",
  "inferences" : [ {
    "conclusion" : "A(a)",
    "ruleName" : "A(X) :- B(X), C(X) .",
    "premises" : [ "B(a)", "C(a)" ]
  }, {
    "conclusion" : "B(a)",
    "ruleName" : "Asserted",
    "premises" : [ ]
  }, {
    "conclusion" : "C(a)",
    "ruleName" : "Asserted",
    "premises" : [ ]
  } ]
}
```
That is, the JSON object has a `finalConclusion` that marks the goal fact of the trace, and a list of rule applications (`inferences`). Each rule application connects body facts (`premises`) to a single head fact (`conclusion`). The `ruleName` is just a string describing the rule application, which would be either the rule that was used, or the keyword "Asserted" to mark facts that are from the input and don't need to be justified further.

**Comment by matzemathics** [comment]
@stefborg if you'd like a quick solution, you can take a look at the python bindings, where the trace is available as a python dictionary. For an example you can take a look at the [corresponding unit test](https://github.com/knowsys/nemo/blob/main/nemo-python/tests/test_example.py#L86C9-L86C19).
