### ISSUE TITLE
Type Error depending on input

### ISSUE THREAD

**Issue by Laschoking** [knowsys/nemo#441]
Consider following example:
```
B(?nr2):-
    A(?nr1,"test"),
    ?nr2 = ?nr1 + 1.
```
Running the following program without imported facts results in:
```
 Invalid type declarations. Arithmetic operations can only be used with numeric types. 
```

When I add facts for `A` inside my program, I do not receive any errors.
``` 
A(1,"test").
B(?nr2):-
    A(?nr1,"test"),
    ?nr2 = ?nr1 + 1.
```
But when I import the CSV-file `A.csv`, with the same fact
``` 
1,"test" 
```
```
@import A[2]: csv{resource = "A.csv"}.
B(?nr2):-
    A(?nr1,"test"),
    ?nr2 = ?nr1 + 1.
```
i will get an error:
```
ERROR nmo] error: Invalid type declarations. Arithmetic operations can only be used with numeric types.
```

**Comment by monsterkrampe** [comment]
At least for case 3, this is intended behavior. If you use 
```
@import A[int, string]: csv{resource = "A.csv"}.
```
this should work. (The syntax might be different with the new import though, I did not check.)

Case 1 should not produce an error though; have to take a look why it does...
