### ISSUE TITLE
Min/max as built-in arithmetic functions

### ISSUE THREAD

**Issue by stefborg** [knowsys/nemo#442]
Do you plan to support "min" and "max" for arithmetic data types? Then one could write something like
```
E(?x, ?y) :- A(?x, ?z), B(?x, ?u), C(?x, ?v), D(?x, ?w), ?y = min(?z,?u,?v,?w) .
```
I could also write this as 4 different rules with "<="-constraints, but that would not be very readable.

**Comment by monsterkrampe** [comment]
I'm currently working at least on a binary version of this since I also need it :)

**Comment by monsterkrampe** [comment]
When the PR is merged, the way to write your example would be:
```
E(?x, MIN(?z, MIN(?u, MIN(?v, ?w)))) :- A(?x, ?z), B(?x, ?u), C(?x, ?v), D(?x, ?w) .
```
Not perfect with the nested `MIN`s but still better than having multiple rules :)

**Comment by monsterkrampe** [comment]
I missed that @aannleax had been working on this already. After his PR, there is also the n-ary version of the `MAX` and `MIN` functions :)
