### ISSUE TITLE
Error output: Add line number & relation

### ISSUE THREAD

**Issue by Laschoking** [knowsys/nemo#447]
When receiving an error like:
`error: Overloading of predicate names by arity is currently not supported.`
it would be good, to output the line number and relation which caused he error.

**Comment by Laschoking** [comment]
Another case is when I try to output a relation that does not exist (i.e. because of a typo), I receive the imprecise error message :
`thread 'main' panicked at nemo/src/execution/execution_engine.rs:783:26:
all predicates should have a type by now`

**Comment by monsterkrampe** [comment]
Likely addressed in #455.
