### ISSUE TITLE
negation error with constants inside the negated atom

### ISSUE THREAD

**Issue by Laschoking** [knowsys/nemo#452]
Using constants in negated atoms does not work, when there is more than 1 negated atom per rule.
In the example I use string constants, but it is the same with integers.

1.  Error, when using one constant `"a"` in 2 negated atoms:
```
C(?a,?a0,?a1):-
    A(?a,?a0,?a1),
    ~ B(?a,?a0),
    ~ B("a",?a1).
```
2.   Error, when using two constants in 2 negated atoms:
```
C(?a,?a0,?a1):-
    A(?a,?a0,?a1),
    ~B("a",?a0),
    ~B(?"a",?a1).
```

The error message is:
```
thread 'main' panicked at nemo/src/execution/planning/arithmetic.rs:38:26:
Variable order must contain an entry for every variable.
```

The error also triggers, when the two negated atoms are referring to  different relations (i.e. replace the second negated atom with `~D("a",?a1)` and it will still not work).

**Comment by matzemathics** [comment]
this is likely also related to #446, which definitely needs to be addressed for the next release
