### ISSUE TITLE
Numeric functions should support all numeric datatypes, possibly mixed

### ISSUE THREAD

**Issue by mkroetzsch** [knowsys/nemo#467]
Nemo supports three numeric types with disjoint value spaces: integer, double, and float. Numeric functions currently require all arguments to have the same type, and they also return a value of this type. Nemo should follow the[ XML Schema type promotion rules](https://www.w3.org/TR/xpath-31/#promotion) to convert numbers to compatible types in such cases. These are the rules that are also used in SPARQL for this task.

Besides allowing mixed types, this would also allow the use of trigonometric functions on integers without explicit conversion.

**Comment by aannleax** [comment]
Implemented in #474
