### ISSUE TITLE
Of-by-one error in SUBSTRING function

### ISSUE THREAD

**Issue by eilmiv** [knowsys/nemo#481]
The following program
```
s("abc") .
x(SUBSTRING(?s, 0, 1)) :-  s(?s) .
x(SUBSTRING(?s, 1, 1)) :-  s(?s) .
x(SUBSTRING(?s, 2, 1)) :-  s(?s) .
```
results in `x("a")` and `x("b")` but not `x("c")`. 

There should be a `>` instead of `>=` [here](https://github.com/knowsys/nemo/blob/bc3fae265e966e16fb049a9a4bd7f8e771dba347/nemo-physical/src/function/definitions/string.rs#L396).

**Comment by monsterkrampe** [comment]
@eilmiv feel free to submit a PR :)
