### ISSUE TITLE
Non-monotonic behavior when dealing with mixed types

### ISSUE THREAD

**Issue by stefborg** [knowsys/nemo#483]
This problem was found by Timon Hoschke while working on a student project, using the online demo of nemo (v0.5.1-dev):

The program
```
rep(2, 2) .
P(1) .
P(3) .

P(?i) :- rep(?i, _), P(?k), P(?l), ?i >= ?k, ?i <= ?l, ?l - ?k < 3 .

@output P .
```
correctly produces the fact `P(2)`.

When we add the three facts
```
rep(-10, "a") .
rep(-2, -2) .
P(-2) .
```
then `P(2)` is not derived anymore.

When we remove any one of the additional three facts, `P(2)` is derived again. The same happens when `"a"` is replaced by any integer, although the rule does not even use the second component of `rep`.

We can only speculate that this happens because we use an integer as well as a string in the second component of `rep`. Do you have any idea what is going on here?

**Comment by matzemathics** [comment]
@stefborg this is the same issue as #431, which essentially causes projection to not work correctly, when multiple data-types occur in some columns of a table. This is fixed by #482, which is already approved.

@mkroetzsch maybe we should do a 0.5.1 release for this.
