### ISSUE TITLE
`SUBSTRING` should gracefully handle excessive length

### ISSUE THREAD

**Issue by mmarx** [knowsys/nemo#492]
`SUBSTRING("foo", 1, 23)` currently results in the empty string. To be more in line with how, e.g., SPARQL handles this, we would like it to return `"oo"` instead, i.e., `SUBSTRING(s, i, l)` should return *at most* `l` characters of `s` starting from `i`.

Indexing should also be 1-based, as in SPARQL.

**Comment by MLHilsen** [comment]
```
def SUBSTRING(str, i, j):
    if j > len(str):
        return str[i:]
    return str[i:j]
```
