### ISSUE TITLE
String methods should handle non-ascii characters

### ISSUE THREAD

**Issue by aannleax** [knowsys/nemo#493]
The current implementation of the string functions does not properly handle non-ascii characters. For example
```
word("loẅks").
count(STRLEN(?X)) :- word(?X).
```

returns `count(7)`.

Possibly, this is a good crate to use: https://docs.rs/unicode-segmentation/latest/unicode_segmentation/

**Comment by aidan-bailey** [comment]
I can have a look at this?

**Comment by aannleax** [comment]
> I can have a look at this?

Sure, go ahead :)
