### ISSUE TITLE
TSV and DSV formats use the wrong file extension

### ISSUE THREAD

**Issue by Laschoking** [knowsys/nemo#559]
Currently `@export Test :- tsv{}.` results in the creation of the new table `Test.csv`.
It would be more clear if the extension was `.tsv`

**Comment by mmarx** [comment]
Looks like this got broken when moving the constants to `syntax.rs`:
https://github.com/knowsys/nemo/blob/379844dd7b279e2d37c4ea9afd0d0bc9dd71c6ef/nemo/src/syntax.rs#L390-L393
