### ISSUE TITLE
Implement handling of prefixes in the rule parser

### ISSUE THREAD

**Issue by mmarx** [knowsys/nemo#61]
The prefix handling code in the rule parser is currently incomplete. While prefixes are taken into account on parsing, there is, e.g., currently no way to obtain the original IRIs from a `PrefixedName`.

Depends on #58 being merged.

**Comment by monsterkrampe** [comment]
While the possibility of retaining prefixes should become easier after the ongoing parser rework, 
Currently, we do not plan to have this feature though as we do not see the need for it.
We will reopen the issue if this should change in the future.
