### ISSUE TITLE
Excise Rule Filters for Constants and Duplicate Variables from the Rule Model

### ISSUE THREAD

**Issue by monsterkrampe** [knowsys/nemo#64]
Technical Debt from #62.

Support for constants and duplicate variables is currently implemented using filters in a very hacky way in the execution engine.
I did not look into the code in detail yet so I cannot make an informed proposal on how to improve this.

Maybe @aannleax has ideas on this already?

**Comment by monsterkrampe** [comment]
I wonder if this issue is obsolete by now or at least dominated by other efforts regarding changes in the rule representation.

**Comment by mmarx** [comment]
At least for the rule model, we want to stay true to the original input, so rewritings like getting rid of duplicate variables should not happen there yet.

**Comment by monsterkrampe** [comment]
This will be released in `0.4.0` now, right?
