### ISSUE TITLE
usize vs u32 vs u64 for the Dictionary

### ISSUE THREAD

**Issue by ellmau** [knowsys/nemo#69]
There has been a conversation about the choice of the Datatype of the `Dictionary` indices. It should be discussed on due time.
> > Apart from this discussion on `usize`/`u64` (which we should probably decide on in the group) and the small changes above, this looks good, though.
> 
> Thank you for the thoughtful review, did all the changes except the `usize` vs `u32`/`u64` issue

> > I see your concern. It is possible to refactor the Dictionary trait to be either u64 or u32.
> > My thoughts have been to utilize the native number representation of the machine.
> 
> `usize` is not about being the native representation, its sole point is to cover the whole range of allowable pointer values. Even i386 has 64-bit-registers, so `u64` could also be considered “native” there.

It is still something to consider when using indices, as indices are always `usize`. I wanted to avoid unnecessary casting back and forth when I've designed the `Dictionary` treat.

_Originally posted by @ellmau in https://github.com/knowsys/stage2/issues/68#issuecomment-1322149088_

**Comment by mmarx** [comment]
I guess this is settled for now?
